### ISSUE TITLE
Correcciones y consejos

### ISSUE THREAD

**Issue by Liluminalia** [g0nzu/202301-W3CH3-Gonzu-Diez#3]
Buenas Gonzu! creo que el enlace de sonar esta mal, me lleva como a la información tuya y no realmente al proyecto, échale un ojo por si esta mal y lo editas porfa.

intenta no llamar a una rama algo tan genérico y poco descriptivo como "feature/typescript" échale un ojo a los comentarios de los commits e intenta dar feedback a lo que te indicamos por aquí! 

animo!

**Comment by g0nzu** [comment]
Okey, perdón! no entiendo por qué hay veces que Sonar analiza y otras que no, le echo un ojo.

**Comment by Liluminalia** [comment]
gonzu... es el issue de la semana pasada... hay que dar feedback, en el día. cierro el issue, mírate los demás para poder cerrarlos...

**Comment by g0nzu** [comment]
Lo sé, pero mejor responder ahora que no hacerlo (?)
